### ISSUE TITLE
peer-to-peer code review 23/09/2021

### ISSUE THREAD

**Issue by Qoosim** [shadabwahidullah/TedxUniversity#4]

**Comment by Qoosim** [comment]
NIce job @shadabwahidullah. You really put a lot to this project and I commend you for the good work.
However, I suggest you create a different file to hold the speaker object and import it to your main.js.
I also suggest to you call the append() method on the body when you are appending more than one element to the body so as to reduce the number of lines of code in your project. Time does not permit me to review the rest, but I believe you are already on point for this project. Good luck with your subsequent project.

**Comment by shadabwahidullah** [comment]
I will make these changes, Thanks for mentioning them.
